### ISSUE TITLE
Blog links giving 404 errors

### ISSUE THREAD

**Issue by robert-bogan** [mhedgpeth/mhedgpeth.github.io#15]
Hi just though to feedback as your blog appeared in my feed
https://hedge-ops.com/about/ , all of the links are giving 404 errors
destination folder moved?

**Comment by mhedgpeth** [comment]
Thanks for the note Robert, we were making changes to the site yesterday. I checked this morning and it looks like it's there. Could you check again on your side?

**Comment by robert-bogan** [comment]
Still not working, main page is up but all links e.g. top link as below give 404 as further below
![image](https://github.com/mhedgpeth/mhedgpeth.github.io/assets/86830153/2381a52b-e05c-4f4b-8333-1f1fa892efe9)
![image](https://github.com/mhedgpeth/mhedgpeth.github.io/assets/86830153/018b64ea-d333-42a1-a0af-d152bf9f66fb)

**Comment by mhedgpeth** [comment]
Thanks again for letting me know. Those links broke as we migrated platforms. It should work now. I appreciate it!
